trigger:
  branches:
    include:
    - master
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      displayName: Build extensions
      inputs:
        targetType: inline
        script: >
          if [ -f extensions.csproj ]

          then
              dotnet build extensions.csproj --output ./bin
          fi
    - task: NodeTool@0
      displayName: Use Node version 10.14.1
      inputs:
        versionSpec: 10.14.1
    - task: Npm@1
      displayName: Install Application Dependencies
      inputs:
        workingDir: $(System.DefaultWorkingDirectory)
        verbose: false
    - task: Npm@1
      displayName: Run 'build' script
      inputs:
        command: custom
        workingDir: $(System.DefaultWorkingDirectory)
        verbose: false
        customCommand: run build --if-present
    - task: Npm@1
      displayName: Remove extraneous packages
      inputs:
        command: custom
        workingDir: $(System.DefaultWorkingDirectory)
        verbose: false
        customCommand: prune --production
    - task: ArchiveFiles@2
      displayName: Archive files
      inputs:
        rootFolderOrFile: $(System.DefaultWorkingDirectory)
        includeRootFolder: false
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'

